### ISSUE TITLE
有个建议

### ISSUE THREAD

**Issue by mecyl** [JiYouMCC/FindGhost#37]
抓爆词不要在发言后

直接踢爆词玩家出局，很容易导致游戏结束。

可以改成在玩家发言的时候，系统发现有爆词就拦截住不发出来，然后提示该玩家修改，直到没有爆词再发出。

**Comment by JiYouMCC** [comment]
如果爆词提醒和白名单功能一起来的话可能要特地设计下

白名单肯定要让玩家知道哪些词是白名单，但是又不能让用户得知对方的词

**Comment by mecyl** [comment]
有提醒功能就不需要白名单了，反正有爆词就发不出来，玩家收到提醒自己会用别的词代替

**Comment by JiYouMCC** [comment]
提醒我直接用了弹出框 可能用户体验不是很好，不过可以先这样
