### ISSUE TITLE
游戏结束, 返回多条重复信息

### ISSUE THREAD

**Issue by BeniZhu** [JiYouMCC/FindGhost#73]
游戏结束, 返回多条重复信息
![image](https://cloud.githubusercontent.com/assets/23545326/22180236/af6b1084-e0a5-11e6-9ae1-5a39eea2b48a.png)

**Comment by JiYouMCC** [comment]
这个我怀疑是卡机造成的，因为重现不了

**Comment by BeniZhu** [comment]
恩，可以观察一段时间， 如果没有就close掉

**Comment by JiYouMCC** [comment]
duplicate with #45
