### ISSUE TITLE
消息增加时间戳

### ISSUE THREAD

**Issue by BeniZhu** [JiYouMCC/FindGhost#77]
怎么显示可以优化...
@JiYouMCC

**Comment by JiYouMCC** [comment]
本来就有时间戳啊

**Comment by BeniZhu** [comment]
<img width="311" alt="2017-01-24 9 59 14" src="https://cloud.githubusercontent.com/assets/23545326/22231028/e7b2b47a-e21b-11e6-8c83-ae43ea3f94bd.png">

**Comment by BeniZhu** [comment]
[http://www.cnblogs.com/zhangpengshou/archive/2012/07/19/2599053.html](http://www.cnblogs.com/zhangpengshou/archive/2012/07/19/2599053.html)

时间格式函数

**Comment by JiYouMCC** [comment]
那个只是渲染的时候我懒得显示了，不然的话系统消息和对话消息就会混在一起，本来时间就在消息里面
要不你设计个格式，可以让对话和系统消息不会混淆的那种还带时间的
