### ISSUE TITLE
集体逃跑/投票结果异常

### ISSUE THREAD

**Issue by mecyl** [JiYouMCC/FindGhost#85]
1. 游戏中突然状态异常，出现所有人员批量离线或者逃跑

2. 投票未结束，某人就被投死了，游戏异常结束

**Comment by JiYouMCC** [comment]
第二个问题已经报过了，我知道怎么回事，就是没空修
第一个问题应该还是有人用了不正常的客户端，触发了clearuser的事件造成的

**Comment by JiYouMCC** [comment]
第一个问题不是状态异常，状态不会异常的，只会事件异常

**Comment by JiYouMCC** [comment]
duplicate with #4 and #46 
全都报过，就是没人改 :sob:

**Comment by JiYouMCC** [comment]
duplicate with #45 also
